name: Tests and code quality

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  pre_job:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'
          skip_after_successful_duplicate: true
  tests:
    name: Code quality, unit tests and code coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
      - name: Run CI task
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HK_FAIL_FAST: true
          HK_STATE_DIR: ${{ runner.temp }}/hk
        run: mise run ci
      - name: Upload lint task output
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: lint-task-results
          path: ${{ runner.temp }}/hk/output.log
          archive: false
